# -*- coding: utf-8 -*-
"""Cópia de MeuPrimeiro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODlnXU8DvSZmGl47VbpbIFI40pQwW1FR

# Operadores Aritméticos
"""

# Adição
10 + 2

# Subtração
10 - 2

# Multiplicação
10 * 2

# Divisão
10 / 2

# Divisão inteira
10 // 2

# Resto da divisão
10 % 2

# Potenciação
10 ** 2

"""# Operadores Relacionais"""

# Menor
10 < 2

# Menor ou igual
10 <= 2

# Maior
10 > 2

# Maior ou igual
10 >= 2

# Igual
7 == 7

# Diferente
7 != 7

"""# Operadores logicos

*   And
*   Or
*   Not

# Tabela verdade
"""

print(10 > 2 and 4 < 6) # V and V - V
print(10 > 2 and 4 > 6) # V and F - F
print(10 < 2 and 4 < 6) # F and V - F
print(10 < 2 and 4 > 6) # F and F - F

""" Or"""

print(10 > 2 or 4 < 6) # V or V - V
print(10 > 2 or 4 > 6) # V or F - V
print(10 < 2 or 4 < 6) # F or V - V
print(10 < 2 or 4 > 6) # F or F - F

""" Not

"""

print(not 10 > 2) # not V - F
print(not 10 < 2) # not F - V
print(not 10 == 2) # not F - V

"""# Variáveis

Variáveis estão alocadas em espaços da memória
"""

# Nome da variável é ''x'' que armazena o valor 10 em um espaço de memória
x = 10
print(x) # Utilizar a referencia no nome atribuido

"""***Regras***

Regras de variáveis


*   Começar com letra (a-z, A-Z) ou sublinhado ( _ )
*   São Case Sensitive (Diferença entre letras maiúscula e minúscula)
*   Exemplo >>> A !=a


Boas práticas para o nome da variável

*   Usar nomes que definam o que ela faz no programa
*   Não usar nomes longos

Tipos de variáveis


*   Não é necessário especificar o tipo de dados quando declarar a variável
*   Python define o tipo de dados na declaração



*   Int (Inteiro) num = 10
*   Float (Real) num = 10.5
*   String (Texto) nome = “Rodrigo”

Boas práticas para o nome da variável

recomendado        
*   soma = 2 + 5       
*   soma_total  = 2 + 5   
*   somaTotal = 2 + 5

Não recomendado

 *   a = 2 + 5
 *   soma_dois_números_inteiros = 2 + 5












"""

Nome = "Gabriel Araujo"
print(Nome)

X = 10
Y = 20
soma = X + Y
print(soma)

x = 10
print('O valor de x é',x)

print('o valor de x é',x,' e o dobro é ',x * 2)

nome = 'Gabriel A'
print('Eu,',nome,'tirei',x,'na prova de matemática')

type(x)
print('x',type(x))

nome = 'Gabriel A'
print('nome',type(nome))

num = '100'
num_convert = int(num)  # Converter variável
print('num',type(num))
print('num_convert',type(num_convert))

num_convert = float(num)  # Converter variável
print('num',type(num))
print('num_convert',type(num_convert))

"""**Input**

* Armadezar a informação digitada pelo usuário em uma variável
* O dado armazenado sempre será um texto

"""

nome = input('Digiti o nome de usuário:')
print(nome)

valor = input('Digite um valor:')
print(valor)

desconto = int(valor) - 5
print(desconto)

"""# Condicional"""

# if
if 5 > 10:
  print('verdade')

# if/else
num1 = 10
num2 = 5
if num1 < num2:
  print('num1 é menor que num2')
else:
  print('num1 é maior que num2')

# if / elif / else
num1 = 10
num2 = 10
if num1 < num2:
  print('num1 é menor que num2')
elif num1 > num2:
  print('num1 é maior que num2')
else:
  print('num1 é igual a num2')

num1 = 10
num2 = 5
num3 = 2
if (num1 > num2) and (num1 > num3):
  print('num1 é o maior número')
else:
  print('num1 não é o maior número')

num1 = 25
num2 = 60
num3 = 30
if (num1 + num3) > num2:
  print('num1 + num3 é maior que num2')
elif num2 > (num1 + num3):
    print('num2 é maior que num1 + num3')
else:
    print('num2 é igual a num1 + num3')

"""# Listas, tuplas e dicionários"""

# Lista
[1,2,3,4,5]

# tuplas
(1,2,3,4,5)

# dicionário
{'num1':1,'num2':2,'num3':3}

"""# Lista"""

lista = ['frango',5,'peixe',3,'queijo',4]
type(lista)
lista.append('batata')
print(lista)
print(lista[1])

"""# Tuplas
não pode haver alterações

# Dicionário
"""

dicionario = {'Gabriel:Araujo':'Riacho fundo 2'}
type(dicionario)
print(dicionario)
(dicionario['data']) = '18/02/1999'
print(dicionario)

"""# Estrutura de repetição
**for**
Estrutura de repetição
Executar comandos, enquanto percorre os itens de uma coleção
Sintaxe:


*   <variável> in <coleção>:
*   <<comandos>>

**Formas de repetição**

*   Simples
*   Range
*   Enumerate

**For - Range**
Exemplo
          >>> for contador in range(0,4):
          >>> print(contador)
          0
          1
          2
          3
**For - Range**
Exemplo
lista1 = ["teste1","teste2"]
                # Exemplo de for simples
                >>> for val in lista1:
                >>> teste1 print(val)
                teste1
                teste2

                # Exemplo de for com Enumerate
                >>> for i, val in enumerate(lista1):
                >>> print(i, val)
                0, teste1
                1, teste2

*For - Operadores Compostos*
*   For - Operadores Compostos
*   Código mais reduzido

Operador:

          Mais igual: +=
          Menos igual -=
          Vezes igual *=
          Dividido igual /=
          Módulo igual  %

Exemplo:

        num += 1: num = num +1
        num -= 2: num = num – 1
        num *= 5: num *= 5
        num *= 5: num = num / 2
        num %= 2 : num = num % 2    


**For -Operadores Compostos**
Exemplo

lista2 = [2, 3, 4]:
                  
                   >>> for val in lista2:
                   >>> val += 1
                   >>> 3 4 5 print(val)
                   3
                   4
                   5
                   Segundo exemplo:
                   >>> for val in lista2:
                   >>> val *= 2
                   >>> print(val)
                   4
                   6
                   8

**While**

Executar comandos enquanto uma condição é verdadeira

Sintaxe:

        >>> while <condição>:
        >>> <<comandos>>

        >>> while <condição>:
        >>> <<comandos>>
        >>> else:
        >>> <<comandos>>

Exemplo:

        # Exemplo de While
        >>> val = 1
        >>> while (val < 6):
        >>> val *=2
        >>> print(val)
        2
        4
        8
        # Exemplo de While com else
        >>> while val < 6:
        >>>     val *=2
        >>> else:
        >>>     print("Valor de val é: ", val)
        Valor de val é: 8
"""

# for Range
for contador in range(10):
  print(contador)

# for Range + Break
 for contador in range(10):
  print(contador)
  if contador == 6:
    break

lista = ['lobo','cachorro','gato','vaca']

# for simples
for val in lista:
  print(val)

# for Enumerate
lista = ['lobo','cachorro','gato','vaca']
for i, val in enumerate(lista):
  print(i,val)

lista2 =[2,4,6]

for val in lista2:
  val += 1
  print(val)

for val in lista2:
  val *= 2
  print(val)

nome = input('digite seu nome')

print('olá '+nome+'!')

senha_permitida = '123456'

senha_usuario = input('digite sua senha')

if senha_permitida == senha_usuario:
  print('senha correta')
else:
    print('senha incorreta')

