# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UP4trAatFDFpSIJ6OVq_uHqp6jQ9j_TV

# Calculadora simples
"""

# Coletando os números
numero1 = int(input('Coloque o primeiro número: '))
numero2 = int(input('Coloque o segundo número: '))
print(numero1 + numero2)

# Define nossa função
def calculate():
    operation = input('''
    Digite a operação matemática que você gostaria de concluir:
    + para Adição
    - para Subtração
    * para Multiplicação
    / para Divisão
    ''')
    numero_1 = int(input('Coloque o primeiro número: '))
    numero_2 = int(input('Coloque o segundo número: '))

    # Adição
    if operation == "+":
        print('{} + {} = '.format(numero_1, numero_2))
        print(numero_1 + numero_2)

    # Subtração
    elif operation == "-":
        print('{} - {} = '.format(numero_1, numero_1))
        print(numero_1 - numero_2)

    # Multiplicação
    elif operation == "*":
        print('{} * {} = '.format(numero_1, numero_2))
        print(numero_1 * numero_2)

    # Divisão
    elif operation == "/":
        print('{} / {} = '.format(numero_1, numero_2))
        print(numero_1 / numero_2)

    else:
        print('Você não digitou um operador válido, execute o programa novamente.')

# Chama calculate() fora da função
calculate()